version: "3.9"
services:
  backend:
    build: backend/.
    volumes: 
      - ./reports-backend/:/tests/reports/
  frontend:
    build: frontend/.
    volumes: 
      - ./reports-frontend/:/tests/reports/