# frozen_string_literal: true

source 'http://rubygems.org'

gem 'cucumber', '~> 3.1.2'
gem 'brazilian_documents'
gem 'parallel_tests'
gem 'json-schema'
gem 'cpf_faker'
gem 'httparty'
gem 'jsonpath'
gem 'rspec'
gem 'faker'
gem 'pry'
gem 'ffi'
